---
variables:
  BUILD_IMAGES_PROJECT: cryptomilk/build-images
  FEDORA_BUILD: buildenv-fedora

tree-sitter/test:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  script:
    - tree-sitter test
  tags:
    - shared
